TrainerNames:
	db "YOUNGSTER@"
	db "BUG CATCHER@"
	db "LASS@"
	db "SAILOR@"
	db "JR.TRAINER♂@"
	db "JR.TRAINER♀@"
	db "POKéMANIAC@"
	db "SUPER NERD@"
	db "HIKER@"
	db "BIKER@"
	db "BURGLAR@"
	db "ENGINEER@"
	db "JUGGLER@"
	db "FISHERMAN@"
	db "SWIMMER@"
	db "CUE BALL@"
	db "GAMBLER@"
	db "BEAUTY@"
	db "PSYCHIC@"
	db "ROCKER@"
	db "JUGGLER@"
	db "TAMER@"
	db "BIRD KEEPER@"
	db "BLACKBELT@"
	db "RIVAL1@"
	db "BLUE@"
	db "CHIEF@"
	db "SCIENTIST@"
	db "BLAINE@"
	db "SOLDIER@"
	db "COOLTRAINER♂@"
	db "COOLTRAINER♀@"
	db "KOGA@"
	db "ICHITAROU@"
	db "HAYATO@"
	db "ENOKI@"
	db "MIKAN@"
	db "TSUKUSHI@"
	db "JUNIOR@"
	db "TOKYO JACK@"
	db "LT.SURGE@"
	db "RIVAL2@"
	db "RIVAL3@"
	db "WILL@"
	db "CHANNELER@"
	db "KAREN@"
	db "LANCE@"
	db "DAD?@"
